version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: survey360_production
      POSTGRES_USER: survey360_user-production
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - static_volume_prod:/app/staticfiles
      - media_volume_prod:/app/media
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume_prod:/app/staticfiles
      - media_volume_prod:/app/media
      - ssl_certs:/etc/ssl/certs
      - ssl_private:/etc/ssl/private
    depends_on:
      - web

  ssl-setup:
    image: alpine
    volumes:
      - ssl_certs:/etc/ssl/certs
      - ssl_private:/etc/ssl/private
    command: >
      sh -c "
        apk add openssl &&
        openssl req -x509 -nodes -days 365 -newkey rsa:2048
        -keyout /etc/ssl/private/survey360.key
        -out /etc/ssl/certs/survey360.crt
        -subj '/C=US/ST=State/L=City/O=Survey360/CN=leadershipremedy.com' &&
        chmod 600 /etc/ssl/private/survey360.key &&
        chmod 644 /etc/ssl/certs/survey360.crt
      "

volumes:
  postgres_data_prod:
  static_volume_prod:
  media_volume_prod:
  ssl_certs:
  ssl_private: