version: '3.8'

services:
  db:
    image: postgres:15
    container_name: survey360_db
    restart: always
    environment:
      POSTGRES_DB: survey360_db
      POSTGRES_USER: survey360_user
      POSTGRES_PASSWORD: survey360_password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U survey360_user -d survey360_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: survey360_web
    restart: always
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  static_volume:
  media_volume: