version: '3.8'

services:
  db:
    image: postgres:15
    container_name: survey360_db_prod
    restart: always
    environment:
      POSTGRES_DB: survey360_production
      POSTGRES_USER: survey360_user-production
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - survey360_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U survey360_user-production -d survey360_production"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: survey360_web_prod
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - static_volume_prod:/app/staticfiles
      - media_volume_prod:/app/media
    depends_on:
      db:
        condition: service_healthy
    networks:
      - survey360_network


volumes:
  postgres_data_prod:
  static_volume_prod:
  media_volume_prod:

networks:
  survey360_network:
    driver: bridge