# Generated by Django 5.0.6 on 2025-08-09 05:29

import django.db.models.deletion
import survey.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('leader_name', models.CharField(max_length=100)),
                ('leader_email', models.EmailField(max_length=254)),
                ('leader_completed_self', models.BooleanField(default=False)),
                ('leader_token', models.CharField(default=survey.models.generate_token, max_length=64, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=survey.models.generate_token, max_length=64, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='survey.survey')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('survey', 'email')},
            },
        ),
        migrations.CreateModel(
            name='SurveyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_token', models.CharField(default=survey.models.generate_token, max_length=64, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_leader', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='survey.survey')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('supervisor', 'Supervisor/Manager'), ('peer', 'Peer/Colleague'), ('teacher', 'Teacher/Staff'), ('student', 'Student'), ('parent', 'Parent/Community Representative'), ('self', 'Self')], max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_leader_self_assessment', models.BooleanField(default=False)),
                ('q2_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q3_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q4_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q5_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q6_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q7_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q8_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q9_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q10_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q11_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q12_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q13_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q14_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q15_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q16_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q17_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q18_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q19_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q20_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q21_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q22_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q23_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q24_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q25_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q26_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q27_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q28_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q29_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q30_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q31_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q32_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q33_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q34_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q35_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q36_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q37_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q38_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q39_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q40_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q41_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q42_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q43_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q44_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q45_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q46_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q47_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q48_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q49_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q50_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q51_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q52_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q53_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q54_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('q55_response', models.CharField(choices=[('significantly_above', 'Significantly above expectations'), ('above', 'Above expectations'), ('slightly_above', 'Slightly above expectations'), ('meets', 'Meets expectations'), ('slightly_below', 'Slightly below expectations'), ('below', 'Below expectations'), ('significantly_below', 'Significantly below expectations')], max_length=50)),
                ('continue_doing', models.TextField(blank=True, verbose_name='What should this leader CONTINUE doing?')),
                ('stop_doing', models.TextField(blank=True, verbose_name='What should this leader STOP doing?')),
                ('start_doing', models.TextField(blank=True, verbose_name='What should this leader START doing?')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='survey.surveyinvitation')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.survey')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StrengthRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(choices=[('guide_others', 'Ability to guide others towards a common goal'), ('oral_communication', 'Possesses excellent oral communication skills'), ('written_communication', 'Possesses effective written communication skills'), ('listener', 'Great listener'), ('express_ideas', 'Expresses ideas clearly'), ('teacher_development', 'Supports teacher professional development'), ('instructional_strategies', 'Supports teachers in implementing effective instructional strategies'), ('build_relationships', 'Ability to build positive relationships with others'), ('collaboration', 'Supports collaboration among all school stakeholders'), ('analyze_challenges', 'Ability to analyze challenges and implement solutions'), ('positive_culture', 'Creates a positive school culture'), ('innovation', 'Promotes and encourages innovation'), ('continuous_improvement', 'Supports and encourages continuous improvement'), ('timely_decisions', 'Makes timely decisions aligned with school mission and goals'), ('inclusive_decisions', 'Decisions encompass the needs of all stakeholders'), ('data_driven', 'Uses data to inform major decisions'), ('manages_emotions', 'Effectively manages emotions'), ('resilient', 'Resilient in effectively navigating change'), ('navigate_challenges', 'Able to navigate challenges and obstacles'), ('clear_vision', 'Has a clear vision for the school'), ('motivate_others', 'Able to motivate others to work towards shared goals'), ('integrity', 'Maintains a high level of integrity'), ('positive_environment', 'Create a positive school environment'), ('committed_learning', 'Committed to learning and growing professionally'), ('research_practices', 'Is up to date on the latest research and best practices')], max_length=100)),
                ('rank', models.IntegerField()),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_rankings', to='survey.surveyresponse')),
            ],
            options={
                'ordering': ['-rank'],
                'unique_together': {('response', 'strength')},
            },
        ),
        migrations.CreateModel(
            name='OpportunityRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity', models.CharField(choices=[('lacks_vision', 'Lacks a clear vision for the school'), ('verbal_communication', 'Struggles to verbally communicate ideas'), ('written_communication', 'Struggles to communicate in written formats'), ('low_morale', 'Leadership contributes to low morale'), ('resistant_change', 'Resistant to change'), ('foster_collaboration', 'Struggles to foster collaboration'), ('lack_trust', 'Leadership promotes a lack of trust among others'), ('address_issues', 'Struggles to address issues effectively'), ('micromanages', 'Micromanages others'), ('inhibits_autonomy', 'Inhibits autonomy and creativity'), ('pd_opportunities', 'Provide more sufficient PD opportunities for all staff'), ('positive_culture', 'Struggles to create a positive school culture'), ('engage_parents', 'Improve skills to effectively engage parents or community'), ('listening_skills', 'Needs to improve listening skills'), ('expressing_ideas', 'Difficulty expressing ideas'), ('delegate', 'Should delegate more effectively (distribution of tasks)'), ('feedback_processes', 'Could improve their feedback processes'), ('problem_solving', 'Could improve their problem solving skills'), ('follow_through', 'Seems to not follow through'), ('diverse_perspectives', 'Could improve their appreciation for diverse perspectives'), ('recognize_others', 'Could recognize others more often')], max_length=100)),
                ('rank', models.IntegerField()),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_rankings', to='survey.surveyresponse')),
            ],
            options={
                'ordering': ['-rank'],
                'unique_together': {('response', 'opportunity')},
            },
        ),
    ]
